# Generated by Django 4.2.7 on 2025-09-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMOAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmo_api_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('bid', models.DecimalField(decimal_places=5, max_digits=10)),
                ('ask', models.DecimalField(decimal_places=5, max_digits=10)),
                ('spread', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
            ],
            options={
                'db_table': 'market_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['currency', 'timestamp'], name='market_data_currenc_191c5a_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_0ff20b_idx')],
            },
        ),
    ]
