# Generated by Django 4.2.7 on 2025-09-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GMOAPILog',
        ),
        migrations.DeleteModel(
            name='MarketData',
        ),
    ]
