# Generated by Django 4.2.7 on 2025-09-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_tradingsession_remove_currency_base_currency_and_more'),
        ('api', '0002_delete_gmoapilog_delete_marketdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='KLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('BID', '売値'), ('ASK', '買値')], max_length=3, verbose_name='価格タイプ')),
                ('interval', models.CharField(choices=[('1min', '1分'), ('5min', '5分'), ('10min', '10分'), ('15min', '15分'), ('30min', '30分'), ('1hour', '1時間'), ('4hour', '4時間'), ('8hour', '8時間'), ('12hour', '12時間'), ('1day', '1日'), ('1week', '1週間'), ('1month', '1ヶ月')], max_length=10, verbose_name='インターバル')),
                ('open_time', models.DateTimeField(db_index=True, verbose_name='開始時刻')),
                ('open', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='始値')),
                ('high', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='高値')),
                ('low', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='安値')),
                ('close', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='終値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klines', to='core.currency', verbose_name='通貨ペア')),
            ],
            options={
                'verbose_name': 'KLineデータ',
                'verbose_name_plural': 'KLineデータ',
                'db_table': 'api_kline',
                'ordering': ['-open_time'],
                'indexes': [models.Index(fields=['currency', 'price_type', 'interval', 'open_time'], name='api_kline_currenc_7afdec_idx')],
                'unique_together': {('currency', 'price_type', 'interval', 'open_time')},
            },
        ),
    ]
