# Generated by Django 4.2.7 on 2025-09-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', '買い'), ('SELL', '売り')], max_length=4)),
                ('size', models.BigIntegerField()),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', '建玉中'), ('CLOSED', '決済済'), ('PARTIAL', '一部決済')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('risk_percent', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('max_positions', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategies',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', '買い'), ('SELL', '売り')], max_length=4)),
                ('size', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('order_type', models.CharField(choices=[('MARKET', '成行'), ('LIMIT', '指値'), ('STOP', '逆指値')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '注文中'), ('EXECUTED', '約定'), ('CANCELLED', 'キャンセル'), ('REJECTED', '拒否')], default='PENDING', max_length=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('execution_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.position')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy'),
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
            options={
                'db_table': 'strategy_performance',
                'ordering': ['-date'],
                'unique_together': {('strategy', 'date')},
            },
        ),
    ]
