# Generated by Django 4.2.7 on 2025-09-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradingSession',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='min_trade_size',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='pip_size',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='quote_currency',
        ),
        migrations.AddField(
            model_name='currency',
            name='display_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
